// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcvxwjfiezarveljzry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY3Z4d2pmaWV6YXJ2ZWxqenJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODUxNDMsImV4cCI6MjA2MjE2MTE0M30.DGhyYikLh-A5vYXGONBKPq4T_LWDGibE9ppz3gBizVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);